client_config_backend: settings
client_config:
  client_id: 339903407254-9njh9985ssbo9almjrmfvo1id9ai7dfm.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive